-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

DROP TABLE users;
Drop TABle files;

-- file definition

CREATE TABLE file (
	id INTEGER NOT NULL, 
	"fileName" VARCHAR(150), 
	"fileSize" VARCHAR(20), 
	"fileType" VARCHAR(15), 
	"fileHash" VARCHAR(70), 
	"localFileIdentifier" VARCHAR(200) NOT NULL, 
	"GoogleFileIdentifier" VARCHAR(150), 
	"OneDriveFileIdentifier" VARCHAR(150), 
	"AWSFileIdentifier" VARCHAR(150), 
	owner INTEGER, 
	"timeUploaded" DATETIME, 
	"isE2E" BOOLEAN, 
	PRIMARY KEY (id), 
	UNIQUE ("localFileIdentifier"), 
	FOREIGN KEY(owner) REFERENCES users (id)
);

CREATE INDEX "ix_fileName_GoogleFileIdentifier_OneDriveFileIdentifier_AWSFileIdentifier_localFileIdentifier" ON
 file ("fileName", "GoogleFileIdentifier", "OneDriveFileIdentifier", "AWSFileIdentifier", "localFileIdentifier");

-- users definition

CREATE TABLE users (
	id INTEGER NOT NULL, 
	username VARCHAR(100), 
	email VARCHAR(150), 
	"hashedPass" VARCHAR(200), 
	role VARCHAR(10), 
	"passSalt" VARCHAR(80), 
	gmail VARCHAR(150), 
	"oneDriveMail" VARCHAR(150), 
	"AWSARN" VARCHAR(150), 
	PRIMARY KEY (id), 
	UNIQUE (username), 
	UNIQUE (email), 
	UNIQUE (gmail), 
	UNIQUE ("oneDriveMail"), 
	UNIQUE ("AWSARN")
);

CREATE INDEX "ix_username_gmail_oneDriveMail_AWSARN" ON 
users (username, gmail, "oneDriveMail", "AWSARN");




--
--
--
--
--
-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- objects to to be modeled: 
/*
- share relationships 
- keys (may require more than 1 table )
*/

-- pepper: 
--b96gcrw88ZS1SyJEJ+73jQ==

-- Additional salts: 


--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'YWRtaW5QYXNzd29yZDEyMyEk'

--b'UGFzc3dvcmQxMjM0JSQ='

--b'YWRtaW5QYXNzd29yZDEyMyEk'

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'Ym9iUGFzc3dvcmQxMjMhJA=='

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'YWRtaW5QYXNzd29yZDEyMyEk'

--b'Ym9iUGFzc3dvcmQxMjMhJA=='

--b'UGFzc3dvcmQxMjM0JSQ='

--b'UGFzc3dvcmQxMjM0JSQ='

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'YWRtaW5QYXNzd29yZDEyMyEk'

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'Ym9iUGFzc3dvcmQxMjMhJA=='

--b'Y2luZHlQYXNzd29yZDEyMyEk'

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'MzNiMjcxYWE1NzJmOGQ4YzE1MWIwMzQ1MzJmYjVlYjA4N2ViMjM1MjAxM2FiMjI5MWM4ZWZmOWQ0ZTMwOWZlMyQ='

--b'MWY2NGVkNzNkMzdlMDdlMjg2ZWJhMDYxZmVhMDU4MDYwYmU3ZjdmZjc1MTYwMDMyNDI0MTQwMzEyNTI1ZjViMSQ='

--b'MzNiMjcxYWE1NzJmOGQ4YzE1MWIwMzQ1MzJmYjVlYjA4N2ViMjM1MjAxM2FiMjI5MWM4ZWZmOWQ0ZTMwOWZlMyQ='

--b'MzNiMjcxYWE1NzJmOGQ4YzE1MWIwMzQ1MzJmYjVlYjA4N2ViMjM1MjAxM2FiMjI5MWM4ZWZmOWQ0ZTMwOWZlMyQ='

--b'dW5pdFRlc3QxMjMhJA=='

--b'dW5pdFRlc3QxMjMhJA=='

--b'dW5pdFRlc3QxMjMhJA=='

--b'dW5pdFRlc3QxMjMhJA=='

--b'dW5pdFRlc3QxMjMhJA=='

--b'dW5pdFRlc3QxMjMhJA=='

--b'dW5pdFRlc3QxMjMhJA=='

--b'dW5pdFRlc3QxMjMhJA=='

--b'dW5pdFRlc3QxMjMhJA=='

--b'dW5pdFRlc3QxMjMhJA=='

--b'dW5pdFRlc3QxMjMhJA=='

--b'dW5pdFRlc3QxMjMhJA=='

--b'dW5pdFRlc3QxMjMhJA=='

--b'dW5pdFRlc3QxMjMhJA=='

--b'dW5pdFRlc3QxMjMhJA=='

--b'dW5pdFRlc3QxMjMhJA=='

--b'dW5pdFRlc3QxMjMhJA=='

--b'dW5pdFRlc3QxMjMhJA=='

--b'dW5pdFRlc3QxMjMhJA=='

--b'dW5pdFRlc3QxMjMhJA=='

--b'dW5pdFRlc3QxMjMhJA=='

--b'dW5pdFRlc3QxMjMhJA=='

--b'dW5pdFRlc3QxMjMhJA=='

--b'dW5pdFRlc3QxMjMhJA=='

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'QUAwYzdmOTUxNGVlMTQwZWQwNDJhZGJhOGQyNTg0MWU0MmRkYjUwN2Y5YjkwZTJkODk5MTIyOWQ0NzgwNzRjZTlkODc5YzkyYmU0NzVhMTNmNDc4Y2MzMjhhNzA5Njk2Yjc1YmNkODg1MjRhMTI0MGQyYTNiZjU0YTFmNDYxYmRhNyQ='

--b'YWRtaW5QYXNzd29yZDEyMyEk'

--b'Ym9iYnlQYXNzd29yZDEyMyEk'

--b'dW5pdFRlc3QxMjMhJA=='

--b'dW5pdFRlc3QxMjMhJA=='

--b'dW5pdFRlc3QxMjMhJA=='

--b'dW5pdFRlc3QxMjMhJA=='

--b'Y2F0aGVyaW5lUGFzc3dvcmQxMjMhJA=='

--b'Ym9iYnlQYXNzd29yZDEyMyEk'

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'YWRtaW5QYXNzd29yZDEyMyEk'

--b'Ym9iYnlQYXNzd29yZDEyMyEk'

--b'Y2luZHlQYXNzd29yZDEyMyEk'

--b'YWxpY2VQYXNzd29yZDEyMyEk'

--b'YWRtaW5QYXNzd29yZDEyMyEk'

--b'Ym9iYnlQYXNzd29yZDEyMyEk'

--b'Y2luZHlQYXNzd29yZDEyMyEk'

--b'YWxpY2VQYXNzd29yZDEyMyEk'
